--[[
╭─╮╷╭┬╮╭─╮╷  ╷ ╷   ╭┬╮╭─╮╶┬╮╭─╴╭─╮╭─╮╶┬╴╭─╴╶┬╮
╰─╮││││├─╯│  ╰┬╯   ││││ │ ││├╴ ├┬╯├─┤ │ ├╴  ││
╰─╯╵╵ ╵╵  ╰─╴ ╵    ╵ ╵╰─╯╶┴╯╰─╴╵╰╴╵ ╵ ╵ ╰─╴╶┴╯
                     ╭─╮╭─╴╶┬╴╶┬╴╷╭╮╷╭─╴╭─╮   
                     ╰─╮├╴  │  │ ││╰┤│╶╮╰─╮   
>   >      >         ╰─╯╰─╴ ╵  ╵ ╵╵ ╵╰─╯╰─╯   
--]]
local Settings = { }

Settings.LoadPreRelease = false -- Load a prerelease for the MainModule? THIS MIGHT BE UNSTABLE!
Settings.DataStoreName = '' -- Change this to something random. IF YOU CHANGE THIS, OLD DATA WILL NOT BE USED!
Settings.DataStoreKey = '' -- Input random characters here. IF YOU CHANGE THIS, ALL DATA WILL BE LOST!

return Settings
