--[[
╭─╮╷╭┬╮╭─╮╷  ╷ ╷   ╭┬╮╭─╮╶┬╮╭─╴╭─╮╭─╮╶┬╴╭─╴╶┬╮
╰─╮││││├─╯│  ╰┬╯   ││││ │ ││├╴ ├┬╯├─┤ │ ├╴  ││
╰─╯╵╵ ╵╵  ╰─╴ ╵    ╵ ╵╰─╯╶┴╯╰─╴╵╰╴╵ ╵ ╵ ╰─╴╶┴╯
                     ╭─╮╭─╴╶┬╴╶┬╴╷╭╮╷╭─╴╭─╮   
                     ╰─╮├╴  │  │ ││╰┤│╶╮╰─╮   
>   >      >         ╰─╯╰─╴ ╵  ╵ ╵╵ ╵╰─╯╰─╯   
--]]
local Settings = { }

Settings.LoadPreRelease = false -- Load a prerelease for the MainModule? THIS MIGHT BE UNSTABLE! 

return Settings
